import React, { useState } from 'react';
import {
  Zap,
  BookOpen,
  CheckCircle2,
  Lock,
  Search,
} from 'lucide-react';
import { MockTest, UserProfile, AttemptReport, MockMode, MockScope } from '../types';
import type { ChapterQuestionCount, SubjectQuestionCount } from '../lib/questionsApi';
import {
  UserPracticeGenerator,
  type PracticeGeneratePayload,
} from './UserPracticeGenerator';

interface CatalogViewProps {
  mockTests: MockTest[];
  userProfile: UserProfile;
  pastReports: AttemptReport[];
  onStartMock: (mock: MockTest) => void;
  onGeneratePractice: (payload: PracticeGeneratePayload) => void;
  practiceBusy?: boolean;
  questionStats?: SubjectQuestionCount[];
  chapterStats?: ChapterQuestionCount[];
  onNavigate: (tab: string) => void;
}

type CatalogTab = 'All' | 'FixedFull' | 'DynamicFull' | 'Subject' | 'Chapter';

function resolveMode(m: MockTest): MockMode {
  return m.mode === 'dynamic' ? 'dynamic' : 'fixed';
}

function resolveScope(m: MockTest): MockScope {
  if (m.scope) return m.scope;
  if (m.kind === 'Chapter' || m.testCategory === 'chapter') {
    return m.chapterName ? 'chapter' : 'subject';
  }
  return 'full';
}

export const CatalogView: React.FC<CatalogViewProps> = ({
  mockTests,
  userProfile,
  pastReports,
  onStartMock,
  onGeneratePractice,
  practiceBusy,
  questionStats = [],
  chapterStats = [],
  onNavigate,
}) => {
  const [selectedTab, setSelectedTab] = useState<CatalogTab>('All');
  const [selectedSubject, setSelectedSubject] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState('');

  const isEntitledBase =
    userProfile.plan === 'Unlimited' || (userProfile.mocksRemaining ?? 0) > 0;

  /** Catalog list: Fixed papers for Fixed/All; hide moderator dynamic blueprints (users self-serve). */
  const filteredMocks = mockTests.filter((m) => {
    if (!m.isPublished) return false;
    const mode = resolveMode(m);
    const scope = resolveScope(m);

    // User-driven dynamic/subject/chapter — do not list moderator dynamic templates
    if (mode === 'dynamic') return false;

    if (selectedTab === 'DynamicFull' || selectedTab === 'Subject' || selectedTab === 'Chapter') {
      return false;
    }
    if (selectedTab === 'FixedFull' && !(mode === 'fixed' && scope === 'full')) return false;
    if (selectedTab === 'All' && mode !== 'fixed') return false;

    if (selectedSubject !== 'All' && selectedTab === 'All') {
      if (m.subject && m.subject !== selectedSubject && m.subject !== 'Combined') return false;
    }

    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      const matchTitle = m.title.toLowerCase().includes(q);
      const matchSubject = m.subject?.toLowerCase().includes(q);
      const matchChapter = m.chapterName?.toLowerCase().includes(q);
      if (!matchTitle && !matchSubject && !matchChapter) return false;
    }
    return true;
  });

  const showGenerator =
    selectedTab === 'DynamicFull' || selectedTab === 'Subject' || selectedTab === 'Chapter';
  const generatorScope: MockScope =
    selectedTab === 'Subject' ? 'subject' : selectedTab === 'Chapter' ? 'chapter' : 'full';

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-8 font-sans">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight flex items-center gap-2">
            <span>Mock Tests</span>
            <span className="text-xs bg-blue-600 text-white px-2.5 py-1 rounded-full font-bold uppercase tracking-wider font-mono">
              Fixed · You generate Dynamic
            </span>
          </h1>
          <p className="text-xs sm:text-sm text-slate-600 mt-1">
            Fixed papers are curated imports. Dynamic, subject-wise, and chapter mocks are generated by you from the question bank.
          </p>
        </div>

        <div className="bg-slate-900 text-white px-4 py-2.5 rounded-2xl flex items-center gap-3 border border-slate-800 shadow-sm shrink-0">
          <div className="p-1.5 bg-cyan-500/20 text-cyan-400 rounded-lg">
            <Zap className="w-4 h-4 fill-current" />
          </div>
          <div className="text-xs">
            <div className="text-slate-400 text-[10px] uppercase font-mono">Current Plan</div>
            <div className="font-bold text-cyan-300">
              {userProfile.plan} Tier •{' '}
              {userProfile.mocksRemaining !== null
                ? `${userProfile.mocksRemaining} Mocks Left`
                : 'Unlimited Mocks'}
            </div>
          </div>
          {userProfile.plan === 'Free' && (
            <button
              onClick={() => onNavigate('payment')}
              className="px-2.5 py-1 bg-amber-500 text-slate-950 font-bold text-[11px] rounded-lg hover:bg-amber-400 transition-colors ml-2 cursor-pointer"
            >
              Upgrade
            </button>
          )}
        </div>
      </div>

      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 bg-white p-4 rounded-2xl border border-slate-200 shadow-xs">
          <div className="flex items-center space-x-1.5 text-xs font-bold w-full sm:w-auto overflow-x-auto pb-1 sm:pb-0">
            {(
              [
                ['All', 'All Fixed'],
                ['FixedFull', 'Fixed Full'],
                ['DynamicFull', 'Dynamic Full'],
                ['Subject', 'Subject-wise'],
                ['Chapter', 'Chapter-wise'],
              ] as const
            ).map(([id, label]) => (
              <button
                key={id}
                onClick={() => setSelectedTab(id)}
                className={`px-3.5 py-2 rounded-xl transition-all cursor-pointer whitespace-nowrap ${
                  selectedTab === id
                    ? id === 'DynamicFull'
                      ? 'bg-violet-600 text-white shadow-xs'
                      : id === 'Subject'
                        ? 'bg-teal-600 text-white shadow-xs'
                        : id === 'Chapter'
                          ? 'bg-emerald-600 text-white shadow-xs'
                          : 'bg-slate-900 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
              >
                {label}
              </button>
            ))}
          </div>

          {!showGenerator && (
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <div className="relative flex-1 sm:w-64 w-full">
                <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search fixed mocks..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 focus:outline-none focus:border-blue-500"
                />
              </div>
            </div>
          )}
        </div>
      </div>

      {showGenerator && (
        <>
          {!isEntitledBase ? (
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 text-sm text-amber-900 space-y-3">
              <p className="font-semibold">Upgrade your plan to generate practice mocks.</p>
              <button
                type="button"
                onClick={() => onNavigate('payment')}
                className="px-4 py-2 bg-amber-500 text-slate-950 font-bold text-xs rounded-xl cursor-pointer"
              >
                View Pricing
              </button>
            </div>
          ) : (
            <UserPracticeGenerator
              scope={generatorScope}
              questionStats={questionStats}
              chapterStats={chapterStats}
              busy={practiceBusy}
              onGenerate={onGeneratePractice}
            />
          )}
        </>
      )}

      {!showGenerator && filteredMocks.length === 0 && (
        <div className="bg-white border border-dashed border-slate-200 rounded-2xl p-10 text-center text-sm text-slate-500">
          No fixed mock papers yet. Admins import Fixed JSON in Admin → Mock Tests. Use Dynamic / Subject /
          Chapter tabs to generate your own papers from the bank.
        </div>
      )}

      {!showGenerator && filteredMocks.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredMocks.map((mock) => {
            const isFreeDemo = mock.id.includes('demo') || mock.coinPrice === 0;
            const isEntitled = isEntitledBase || isFreeDemo;
            const mockReports = pastReports.filter((r) => r.mockId === mock.id);
            const attemptCount = mockReports.length;
            const isCompleted = attemptCount > 0;
            const scope = resolveScope(mock);

            const scopeLabel =
              scope === 'full'
                ? 'Full CEE'
                : scope === 'subject'
                  ? `Subject · ${mock.subject || '—'}`
                  : `Chapter · ${mock.subject || '—'}`;

            return (
              <div
                key={mock.id}
                className="bg-white rounded-2xl border border-slate-200 hover:border-blue-300 hover:shadow-lg transition-all p-6 flex flex-col justify-between space-y-5"
              >
                <div className="space-y-3">
                  <div className="flex items-center justify-between gap-2 flex-wrap">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <span className="text-[10px] font-extrabold px-2.5 py-1 rounded-full uppercase tracking-wider font-mono bg-blue-100 text-blue-800 border border-blue-200">
                        {scopeLabel}
                      </span>
                      <span className="text-[10px] font-extrabold px-2.5 py-1 rounded-full uppercase tracking-wider font-mono bg-slate-100 text-slate-700 border border-slate-200">
                        Fixed
                      </span>
                    </div>

                    <div className="flex items-center gap-1.5 text-[10px] font-bold">
                      {!isEntitled ? (
                        <span className="bg-amber-50 text-amber-800 border border-amber-200 px-2 py-0.5 rounded-lg flex items-center gap-1">
                          <Lock className="w-3 h-3 text-amber-500" />
                          <span>Locked</span>
                        </span>
                      ) : isCompleted ? (
                        <span className="bg-emerald-50 text-emerald-800 border border-emerald-200 px-2 py-0.5 rounded-lg flex items-center gap-1">
                          <CheckCircle2 className="w-3 h-3 text-emerald-500" />
                          <span>Completed</span>
                        </span>
                      ) : (
                        <span className="bg-blue-50 text-blue-800 border border-blue-200 px-2 py-0.5 rounded-lg">
                          Available
                        </span>
                      )}
                    </div>
                  </div>

                  <h3 className="font-bold text-slate-900 text-base leading-snug">{mock.title}</h3>

                  {mock.chapterName && (
                    <div className="text-xs font-semibold text-slate-600 bg-slate-50 p-2 rounded-xl border border-slate-100 flex items-center gap-1.5">
                      <BookOpen className="w-3.5 h-3.5 text-blue-500 shrink-0" />
                      <span className="truncate">{mock.chapterName}</span>
                    </div>
                  )}

                  <p className="text-xs text-slate-500 leading-relaxed">
                    Curated fixed paper with saved question order and negative marking.
                  </p>

                  <div className="grid grid-cols-3 gap-2 pt-1 font-mono text-[11px] text-slate-600">
                    <div className="bg-slate-50 p-2 rounded-lg border border-slate-100 text-center">
                      <span className="block font-bold text-slate-900">{mock.totalQuestions} Qs</span>
                      <span className="text-[9px] text-slate-400">Total</span>
                    </div>
                    <div className="bg-slate-50 p-2 rounded-lg border border-slate-100 text-center">
                      <span className="block font-bold text-slate-900">
                        {mock.durationSec >= 3600
                          ? `${Math.floor(mock.durationSec / 3600)} Hrs`
                          : `${Math.floor(mock.durationSec / 60)} Mins`}
                      </span>
                      <span className="text-[9px] text-slate-400">Duration</span>
                    </div>
                    <div className="bg-slate-50 p-2 rounded-lg border border-slate-100 text-center">
                      <span className="block font-bold text-rose-600">{mock.wrongMarks}</span>
                      <span className="text-[9px] text-slate-400">Neg Mark</span>
                    </div>
                  </div>

                  <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500 font-semibold">
                    <span>Attempt Count:</span>
                    <span className="font-mono bg-slate-100 text-slate-800 px-2 py-0.5 rounded-lg font-black">
                      {attemptCount} attempts
                    </span>
                  </div>
                </div>

                <div className="pt-2 border-t border-slate-100 space-y-2">
                  {isEntitled ? (
                    <button
                      onClick={() => onStartMock(mock)}
                      className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs rounded-xl shadow-xs transition-all flex items-center justify-center gap-2 cursor-pointer"
                    >
                      <Zap className="w-4 h-4 fill-current" />
                      <span>Start Timed Attempt</span>
                    </button>
                  ) : (
                    <button
                      onClick={() => onNavigate('payment')}
                      className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer border border-slate-300"
                    >
                      <Lock className="w-4 h-4 text-amber-600" />
                      <span>Upgrade Plan to Unlock</span>
                    </button>
                  )}

                  <div className="text-center text-[10px] text-slate-400">
                    {isFreeDemo ? 'Free Demo Mock for all aspirants' : '1 Quota / Mock Deduction upon Start'}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
