/**
 * Bundle Express API → server.js (Hostinger entry).
 * Plain Node ESM — no tsx / no runtime esbuild spawn.
 */
import * as esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'server.js');

await esbuild.build({
  entryPoints: [path.join(root, 'server', 'index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  outfile,
  packages: 'external',
  logLevel: 'info',
  banner: {
    js: '/* GENERATED by scripts/build-server.mjs — source: server/index.ts — do not edit */\n',
  },
});

// Also keep a copy under dist-server for clarity / backups
const copyDir = path.join(root, 'dist-server');
fs.mkdirSync(copyDir, { recursive: true });
fs.copyFileSync(outfile, path.join(copyDir, 'index.js'));

console.log('Wrote Hostinger entry:', path.relative(root, outfile));
